apiVersion: v1
kind: Pod
metadata:
  annotations:
  name: demo
  namespace: default
spec:
  containers:
  - command:
    - sleep
    - infinity
    image: ishaansehgal99/llama-2-7b-chat:latest
    name: main
    resources:
      limits:
        nvidia.com/gpu: "1"
      requests:
        nvidia.com/gpu: "1"
  tolerations:
  - effect: NoSchedule
    key: sku
    operator: Equal
    value: gpu
  - effect: NoSchedule
    key: nvidia.com/gpu
    operator: Exists
